### PR TITLE
clears input when new componet mounts

### PR DESCRIPTION
**Pull request by cmruss**
# Description

[TRY ME](https://clear-input.d1ms51d9oybzjy.amplifyapp.com/)

- Clears searchTerm on component mount
- Leaves query text for optional further search
- Adds delete button to clear input
- ~Removes movies from explore if already rated~

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [ ] Manual testing, deployments 

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by moviedatascience** [comment]
Now my explore page is only two movies lol
22F9BC42-100D-46EF-9197-CD5D9446A1AA

Can we have the initial load with movies until it hits that initial number we had?

**Comment by cmruss** [comment]
> Now my explore page is only two movies lol

Well. Someone's rated a lot of movies.

If you logout and login again does anything change?

**Comment by moviedatascience** [comment]
Also how difficult is implementing taking the recommendations out if they are in your watchlist?

**Comment by moviedatascience** [comment]
> If you logout and login again does anything change?

It does not

**Comment by cmruss** [comment]
> Also how difficult is implementing taking the recommendations out if they are in your watchlist?
It's the same as removing from rated films from explore, so buggy..
My hesitance to remove things is still present, I'd rather let the user know where these things are and stand, than erasing them from other components.

**Comment by cmruss** [comment]
> Can we have the initial load with movies until it hits that initial number we had?

I don't catch your drift friendo?

**Comment by moviedatascience** [comment]
> I don't catch your drift friendo?

Yeah that was worded terribly. 

I just mean we initially loaded 50, right? Could we just have it load until it hits that 50 mark while subtracting out the movies they have already rated?

**Comment by moviedatascience** [comment]
> My hesitance to remove things is still present, I'd rather let the user know where these things are and stand, than erasing them from other components.

I agree in spirit, I've just realized after using it for a while that it becomes somewhat annoying to always be recommended movies you already indicated you wanted to watch. Plus it's not like I can ask it to give me more recommendations. If it's keeping something on there that I already added to the watchlist, that movie is taking up the slot of some other movie that I could also really be interested in.

**Comment by cmruss** [comment]
> > I don't catch your drift friendo?
> 
> Yeah that was worded terribly.
> 
> I just mean we initially loaded 50, right? Could we just have it load until it hits that 50 mark while subtracting out the movies they have already rated?

Hmm, I take your point. Those omitted movies are still taking up space, when they shouldn't, gull dangit.

**Pull request merged**
