### PR TITLE
Configuring Analytics

### PR DESCRIPTION
**Pull request by briannakeune**
# Description

To manually test this feature please log into our analytics site in the docs, _if you have access_, and look through the data points we can collect while testing it out on this [staged version](https://analytics.d1ms51d9oybzjy.amplifyapp.com/).

Setting up Google Analytics and setting up AWS routing.

The routing on AWS was solved, and I have Google Analytics setup to easily take in whatever we'd like to configure it to. _And we might not have to do anything extra_ 😉

If you'd like to look at the analytics please look at this [notion page](https://www.notion.so/React-and-Google-Analytics-0a892b34eee0443c8e6c17ae036fdd78) to find any documentation for that.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] Test A

`// testing that App is rendered
it("renders App component", () => {
  const { container } = render(<App />);
  const component = getAllByTestId(container, "App-component");
  expect(component.length).toBe(1);
});`

- [x] Test B

`// creating a mock function to test if GA initialization was called.
import reactGAinitialization from "./config/analytics.js";
jest.mock("./config/analytics.js");
reactGAinitialization.mockImplementation(() => () => null);
it("calls reactGAinitialization once", () => {
  render(<App />);
  expect(reactGAinitialization).toBeCalled();
});`

# Checklist

- (Not applicable)My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by briannakeune** [comment]
Most of the commits are garbage trials on the staging deployment. Please refer to the documentation if you have any questions or commits after this point.

To be ready to merge this request I would love to:

- [ ] Make sure we do not want anything configured from the start
- [ ] Update AWS env variables once our domain is successfully verified

I think that's pretty much it. Please let me know if you think this will need anything else for our first RC.

**Comment by robomantis19** [comment]
I thought it was pretty good

**Comment by moviedatascience** [comment]
Not really sure what the staged version is pointing to currently. 

I checked off that the code has been reviewed by at least one peer since @robomantis19 seems to have looked it over. 

"signup/register button has been clicked or if they used the links to Letterboxd or IMDb" How difficult would this be to implement? I think Parth would like to see any and all analytics data that we could get up and running for now.

**Comment by briannakeune** [comment]
The staged version was pointing to pages to let everyone know that routing was working, and that I could see the analytics were working correctly, because that has to be deployed and not on the development environment. 

So today I'll focus on 
- [ ] Changing where the analytics are pointing to groa.us
- [ ] Add _Signup_ and a _bounce_ event

Did you not want to use the posthog you posted? That looked pretty sweet.

**Pull request merged**
