### PR TITLE
Rate imdb movies, search imdb movies, polish

### PR DESCRIPTION
**Pull request by cmruss**
# Description

[TRY ME](https://rate-imdb-movies.d1ms51d9oybzjy.amplifyapp.com)

Adds functionality:
- to GET most IMDb movies
- to quickly search through IMDb movies, uses debouncer function to restrict number of redux actions called during onChange.
- to add IMDb movies to ratings and watchlist
- to request ratings and watchlist data on login and save it to state
- to display if a film in Explore is in your ratings or watchlist

Aesthetics:
- Makes the movie cards responsive
- Keeps aspect ratio of images and cards

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change Status

- [x] Complete, but not tested (may need new tests)

# How Has This Been Tested?

- [x] Manual testing/ deployment only to this point

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by moviedatascience** [comment]
```Keeps aspect ratio of images and cards``` This one was very nice and greatly improves overall aesthetics, thank you!

I did notice that the movies being returned on the `Explore` page are ones I have already rated, but that can be addressed in a future PR. Merging this one since it's so clean !

**Comment by moviedatascience** [comment]
Also have no idea if it's possible to have the search bar clear when you navigate to any new page, but because it currently doesn't clear if you've searched for something in explore and click to Recommendations it is auto-filtering your recommendations by that search item.

**Comment by cmruss** [comment]
> Also have no idea if it's possible to have the search bar clear when you navigate to any new page, but because it currently doesn't clear if you've searched for something in explore and click to Recommendations it is auto-filtering your recommendations by that search item.

Hmm yes, good point, I'll jump on that.

**Comment by cmruss** [comment]
> This clearly defaults to Null but in practice it pulls my actual ratings of the movie.
> 
> Which is 100% better than just having them all fill to 5 stars. I think honestly it would look weird to have them appear without a rating, so this is for the best.

We could also populate avg_rating and fill with that, it's just not initially intuitive that it's there for you to alter.

**Comment by moviedatascience** [comment]
> We could also populate avg_rating and fill with that, it's just not initially intuitive that it's there for you to alter.

I think leaving it how it is now is good. Down the road we may adjust, but for now I think it works. There is some latency between a rating being given on the Explore page and it actually staying rated if you navigate away and then back to the page, but that is also not too big of an issue. 

I think the one big problem that remains is that movies aren't filtered out of explore if they are already in your ratings page. BUT we also don't really have a way to remove a rating (if you clicked it by accident, for example). So it may not be wise to have everything leave the explore page if it's already on your ratings page.

**Comment by cmruss** [comment]
> > We could also populate avg_rating and fill with that, it's just not initially intuitive that it's there for you to alter.
> 
> I think leaving it how it is now is good. Down the road we may adjust, but for now I think it works. There is some latency between a rating being given on the Explore page and it actually staying rated if you navigate away and then back to the page, but that is also not too big of an issue.
> 
> I think the one big problem that remains is that movies aren't filtered out of explore if they are already in your ratings page. BUT we also don't really have a way to remove a rating (if you clicked it by accident, for example). So it may not be wise to have everything leave the explore page if it's already on your ratings page.

We could implement delete rating in a snap, as it already functions for watchlist.  

On the explore page; 

I think it would be easy to remove them from the list, which reminds me, I should definitely make sure that is implemented in recommendations. Once that's done, then we can just reuse the method here. 

Just, It could be confusing to search a movie you'd forgotten you'd rated and nothing came up.. in line with the thinking of the gamification aspect, maybe it's a measure of progress? 

If we clear out everything rated from Explore, we should come up with a way to show the user how many ratings, (or whatever's displayed), they've given.. maybe a counter on the page that tells your numbers?

**Pull request merged**
