### PR TITLE
able to add ratings when star is clicked, redux implemented, pertinen…

### PR DESCRIPTION
**Pull request by cmruss**
# Description

User can now add ratings by clicking the star component on each recommendation. 

[TRY ME](https://ratings-redux.d1ms51d9oybzjy.amplifyapp.com/)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [x] Tests refactored to allow for redux, all passing
- [x] Manual testing on deployment returns success message

# Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by moviedatascience** [comment]
I can add stars and then update recommendations, however I will occasionally get back the same movies I have rated. 

These same movies will be recommended with no rating attached to them.

**Comment by moviedatascience** [comment]
Ideally I think the flow should  be that the user rates a movie, that card is removed, the same movie is added to the <rated> page and a replacement recommendation is put in place of the rated movie. 

But maybe the scope of that is too big for this PR? If so then I can merge this, as it seems the functionality for clicking the stars and having them fill in is there.

**Comment by cmruss** [comment]
> I can add stars and then update recommendations, however I will occasionally get back the same movies I have rated.
> 
> These same movies will be recommended with no rating attached to them.

This seems to be from the date not being specific enough in the database, I have requested that we change from it's current format of YYYY-MM-DD to a timestamp, so that the newest result is always returned, not just the first one the query happens to grab for that given date.

**Comment by cmruss** [comment]
> Ideally I think the flow should be that the user rates a movie, that card is removed, the same movie is added to the page and a replacement recommendation is put in place of the rated movie.
> 
> But maybe the scope of that is too big for this PR? If so then I can merge this, as it seems the functionality for clicking the stars and having them fill in is there.

Going forward yes, but yeah, I'm not sure how much that would take to implement that exact idea, I think that could be it's own feature branch.

**Pull request merged**
