### PR TITLE
Mobile Refactor Sign-up

### PR DESCRIPTION
**Pull request by Steven-matos**
# Description
Refactoring the Sign-up page to be present in the mobile view for the page.

[TRY ME](#add your staged deployment link here)

Fixes # (issue) <-- this is for issue numbers from GitHub,
if squashing a bug from Trello, please add a link to that card here instead

Please add a list of what someone reviewing the PR
should be expecting from this PR.
This will include the

- functionality you created/updated
- packages you added and why you added them
- documentation you added

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by Steven-matos** [comment]
[Refactor Register component to functional component](https://trello.com/c/n0gn5G4r/256-refactor-register-component-to-functional-component)

**Comment by moviedatascience** [comment]
@jvillalp had you finished with the styling that this PR needs?

**Comment by jvillalp** [comment]
Still working on the styling, but will let you know once it is complete.

**Comment by msinnema33** [comment]
Will add the new min pwd length into Okta refactor PR

**Pull request merged**
